'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("aviorcom_testRemote2")>  _
        Public Property MySQL_user() As String
            Get
                Return CType(Me("MySQL_user"),String)
            End Get
            Set
                Me("MySQL_user") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("123$P@SSW0RD")>  _
        Public Property MySQL_pass() As String
            Get
                Return CType(Me("MySQL_pass"),String)
            End Get
            Set
                Me("MySQL_pass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("162.214.108.202")>  _
        Public Property MySQL_svr() As String
            Get
                Return CType(Me("MySQL_svr"),String)
            End Get
            Set
                Me("MySQL_svr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("aviorcom_sodcommerce")>  _
        Public Property MySQL_db() As String
            Get
                Return CType(Me("MySQL_db"),String)
            End Get
            Set
                Me("MySQL_db") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3306")>  _
        Public Property MySQL_port() As String
            Get
                Return CType(Me("MySQL_port"),String)
            End Get
            Set
                Me("MySQL_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ECOMMERCE")>  _
        Public Property ImportDefaultCust() As String
            Get
                Return CType(Me("ImportDefaultCust"),String)
            End Get
            Set
                Me("ImportDefaultCust") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11")>  _
        Public Property ImportDefaultRep() As String
            Get
                Return CType(Me("ImportDefaultRep"),String)
            End Get
            Set
                Me("ImportDefaultRep") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E-SHIPPING")>  _
        Public Property ImportDefaultShipping() As String
            Get
                Return CType(Me("ImportDefaultShipping"),String)
            End Get
            Set
                Me("ImportDefaultShipping") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.4.50;Initial Catalog=GSC_STORE_DB;Persist Security Info=True;U"& _ 
            "ser ID=sa;")>  _
        Public ReadOnly Property GSC_STORE_DBConnectionString() As String
            Get
                Return CType(Me("GSC_STORE_DBConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=DVO_STORE_DB;Persist Security Info=True;Use"& _ 
            "r ID=sa;Password=admin1234;Encrypt=True;TrustServerCertificate=True")>  _
        Public ReadOnly Property DVO_STORE_DBConnectionString() As String
            Get
                Return CType(Me("DVO_STORE_DBConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=DVO_STORE_DB;Persist Security Info=True;Use"& _ 
            "r ID=sa;Password=admin1234;Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property DVO_STORE_DBConnectionString1() As String
            Get
                Return CType(Me("DVO_STORE_DBConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SPU-PROGRAMMER;Initial Catalog=DVO_STORE_DB;User ID=sa;Password=admin"& _ 
            "1234;Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property DVO_STORE_DBConnectionString2() As String
            Get
                Return CType(Me("DVO_STORE_DBConnectionString2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=DVO_STORE_DB;User ID=sa;Password=admin1234;"& _ 
            "Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property DVO_STORE_DBConnectionString3() As String
            Get
                Return CType(Me("DVO_STORE_DBConnectionString3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-FSD465OI;Initial Catalog=DVO_STORE_DB;User ID=sa;Password=admi"& _ 
            "n123;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True")>  _
        Public ReadOnly Property DVO_STORE_DBConnectionString4() As String
            Get
                Return CType(Me("DVO_STORE_DBConnectionString4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MSI;Initial Catalog=DVO_STORE_DB;Integrated Security=True;Connect Tim"& _ 
            "eout=30;Encrypt=True;TrustServerCertificate=True")>  _
        Public ReadOnly Property DVO_STORE_DBConnectionString5() As String
            Get
                Return CType(Me("DVO_STORE_DBConnectionString5"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.WorkOrderEntry.My.MySettings
            Get
                Return Global.WorkOrderEntry.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
