USE [QUEUEING_DB]
GO

/****** Object:  Table [dbo].[Queueing]    Script Date: 12/1/2020 11:14:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Queueing](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[OrderID] [bigint] NULL,
	[Status] [int] NULL,
	[GroupTo] [int] NULL,
 CONSTRAINT [PK_Queueing] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


